# This workflow builds and releases the Python application for Windows and macOS.
name: Release (Windows + macOS)

on:
  push:
    tags:
      - "v*" # Trigger the workflow when a tag starting with 'v' is pushed
  workflow_dispatch: {} # Allows manual triggering

permissions:
  contents: write # Required to create a GitHub Release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Install PyInstaller
        run: pip install pyinstaller

      # [수정 3] src 폴더로 이동한 후 PyInstaller를 실행하여 경로 문제를 근본적으로 해결합니다.
      - name: Build with PyInstaller
        shell: pwsh
        run: |
          cd src
          pyinstaller main.py --onefile --noconsole `
          --hidden-import sync --hidden-import ui --hidden-import constants `
          --name "${{ github.event.repository.name }}" `
          --distpath out --workpath ../build --specpath ../build --clean

      # [수정 3-1] 작업 디렉토리가 변경되었으므로 결과물 경로를 src/out으로 수정합니다.
      - name: Rename artifact for release
        shell: pwsh
        run: |
          $newName = "${{ github.event.repository.name }}-${{ github.ref_name }}-windows.exe"
          Move-Item -Path "src/out/${{ github.event.repository.name }}.exe" -Destination "src/out/$newName"

      # [수정 3-2] 업로드할 아티팩트 경로를 src/out으로 수정합니다.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifact
          path: src/out/*.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install PyInstaller
        run: pip install pyinstaller

      # [수정 3] src 폴더로 이동한 후 PyInstaller를 실행하여 경로 문제를 근본적으로 해결합니다.
      - name: Build with PyInstaller
        run: |
          cd src && pyinstaller main.py --onefile --noconsole \
          --hidden-import sync --hidden-import ui --hidden-import constants \
          --name "${{ github.event.repository.name }}" \
          --distpath out --workpath ../build --specpath ../build --clean

      # [수정 3-1] 작업 디렉토리가 변경되었으므로 결과물 경로를 src/out으로 수정합니다.
      - name: Zip & rename artifact
        run: |
          NAME="${{ github.event.repository.name }}"
          TAG="${{ github.ref_name }}"
          # 실행 파일 자체의 이름을 먼저 변경
          mv "src/out/${NAME}" "src/out/${NAME}-${TAG}-macos"
          # zip 압축
          (cd src/out && zip -r "${NAME}-${TAG}-macos.zip" "${NAME}-${TAG}-macos")
          # 원본 실행 파일 삭제
          rm -rf "src/out/${NAME}-${TAG}-macos"

      # [수정 3-2] 업로드할 아티팩트 경로를 src/out으로 수정합니다.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifact
          path: src/out/*.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos] # Wait for both builds to complete
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true # Merge artifacts from different jobs into one directory
          pattern: "*-artifact"

      - name: Generate release notes
        run: |
          {
            echo "## Release Notes for ${{ github.ref_name }}"
            echo ""
            echo "This is an automated release. See below for downloadable assets."
            echo ""
            echo "### Assets"
            echo "A list of files included in this release:"
            ls -l dist
          } > NOTES.md

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: NOTES.md
          files: |
            dist/*.exe
            dist/*.zip

