name: Build & Release (Windows + macOS)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # 릴리즈 생성/업데이트에 필요

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Install PyInstaller (latest)
        run: pip install pyinstaller
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller main.py --onefile --noconsole
        shell: bash

      - name: Rename artifacts
        run: |
          mkdir -p out
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/*.exe "out/${{ github.event.repository.name }}-${{ github.ref_name }}-windows.exe"
          else
            # macOS: 실행 파일 (단일 바이너리). .app 번들 원하면 py2app 사용(아래 안내).
            mv dist/* "out/${{ github.event.repository.name }}-${{ github.ref_name }}-macos"
